#fly.toml app configuration file generated for aiolists on 2025-06-16T11:15:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aiolists'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
